services:
  - type: web
    name: figueroa-coach-api
    env: node
    plan: free
    region: oregon
    buildCommand: "npm install"
    startCommand: "node src/server.js"
    envVars:
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "3306"
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: FRONT_ORIGIN
        sync: false
